repos:
  - repo: local
    hooks:
      - id: stagedfright
        name: stagedfright
        language: system
        entry: stagedfright .stagedfright
        verbose: true
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3
      types:
        - python
